### ISSUE TITLE
Feature request: Support for Third-Party API Providers like OpenRouter

### ISSUE THREAD

**Issue by wewewexiao2008** [glowingjade/obsidian-smart-composer#103]
Hey! 👋 Currently, the plugin works great (seriously smooth experience!), but I'm looking for better ways to connect with alternative API providers like OpenRouter.

Can you develop some configuration methods or guidelines for users who want to use non-official API endpoints? It would be super helpful to have a flexible setup that allows easy connection to different providers.

**Comment by kevin-on** [comment]
Thanks for the feedback! We'll add support for custom OpenAI endpoints soon. We'll update this issue when ready.
