### ISSUE TITLE
[FR] Add path exclusion for embedding.

### ISSUE THREAD

**Issue by wwjCMP** [glowingjade/obsidian-smart-composer#106]
Add path exclusion for indexing.

**Comment by kevin-on** [comment]
I've added this to the project backlog. You can track it [here](https://github.com/glowingjade/obsidian-smart-composer/issues/106).
Could you clarify - are you looking to exclude files from being indexed, or exclude them when using vault chat?

**Comment by wwjCMP** [comment]
> I've added this to the project backlog. You can track it [here](https://github.com/users/glowingjade/projects/1/views/3). Could you clarify - are you looking to exclude files from being indexed, or exclude them when using vault chat?

Exclude files from being indexed.
