### ISSUE TITLE
feat: Display RAG results

### ISSUE THREAD

**Issue by kevin-on** [glowingjade/obsidian-smart-composer#108]
Allow users to see the sources contributing to the model's output.

**Comment by glowingjade** [comment]
@3-ark Do you mean something like this? https://github.com/brianpetro/obsidian-smart-connections?tab=readme-ov-file#smart-chat-ai-conversations-based-on-your-notes

**Comment by glowingjade** [comment]
@3-ark So the key difference is showing similarity scores, right?

**Comment by glowingjade** [comment]
We have just added a feature to display search results with a similarity score! Check out the updates [here](https://github.com/glowingjade/obsidian-smart-composer/pull/107) and [here](https://github.com/glowingjade/obsidian-smart-composer/pull/118). The release is scheduled for today.

**Comment by glowingjade** [comment]
Thanks for your suggestions!

1. We'll look into a better way to handle the model list.
2. For RAG search results, you can actually customize the limit in the Advanced Configuration settings: https://github.com/glowingjade/obsidian-smart-composer/wiki/1.4-Advanced-Configuration#rag-settings
3. Regarding Jan.ai - while I haven't checked if they support OpenAI-compatible APIs, you can use any provider that does through our custom OpenAI-compatible models option: https://github.com/glowingjade/obsidian-smart-composer/wiki/1.4-Advanced-Configuration#custom-openai-compatible-models
