### ISSUE TITLE
@Folder 

### ISSUE THREAD

**Issue by dxcore35** [glowingjade/obsidian-smart-composer#130]
Please enable to add folder as context.

**Comment by glowingjade** [comment]
You can use folders as context by typing @foldername
https://github.com/glowingjade/obsidian-smart-composer/wiki/2.1-Contextual-Chat#using--to-select-context

**Comment by dxcore35** [comment]
Amazing! I tried it it was not intuitive. As I was expecting trying to write folder path "1.PROJECTS/Project1/" as it is in cursor. But here the search is just based on name. Also the icons are bit small, so I havent noticed folder icon.

**Comment by glowingjade** [comment]
Actually, the search does work with full paths - you can type any part of the folder path to find it.
Thank you for your feedback about the icon size and user experience. We'll look into ways to make this more intuitive in future updates.

**Comment by TfTHacker** [comment]
This is a great feature, but I have to admit, it wasn't intuitive for me either. The lookup didn't find a folder three levels deep, though if I typed it manually and hit enter (somehow bypassing the lookup popup)

**Comment by glowingjade** [comment]
> This is a great feature, but I have to admit, it wasn't intuitive for me either. The lookup didn't find a folder three levels deep, though if I typed it manually and hit enter (somehow bypassing the lookup popup)

Oh, I've tested it and found the same issue. I'll get this fixed soon. Thanks for bringing this to my attention!
