### ISSUE TITLE
[FR] Allow setting of maximum output tokens for AI Chat responses

### ISSUE THREAD

**Issue by maxthraxx** [glowingjade/obsidian-smart-composer#135]
As title says. I am not sure what the max is now, but sometimes longer responses would be better for suggestions (more extensive editing capability).

**Comment by kevin-on** [comment]
Currently we are using 4096 token limit for Anthropic models and other models have no set maximum. Claude 3.5 Sonnet and Haiku supports 8192 output tokens so maybe we can increase it.
