### ISSUE TITLE
CORS Issue When Using Ollama

### ISSUE THREAD

**Issue by websocketbear** [glowingjade/obsidian-smart-composer#138]
Hello! Thank you for creating such an amazing plugin.

After reviewing the ‘1.4-Advanced-Configuration’ documentation, I confirmed that it is possible to configure with Ollama. I proceeded with the setup, but a CORS issue occurred. I added `app://obsidian.md*` to the `OLLAMA_ORIGINS` and executed it, but the same issue persisted. This might be related to a header problem…
<img width="539" alt="스크린샷 2024-11-26 오전 9 55 08" src="https://github.com/user-attachments/assets/c701bea5-37f4-42e2-876e-31019ccdf1f8">

For reference, the `copilot` plugin works well with Ollama. Interestingly, that plugin has a checkbox for automatic CORS configuration. Adding a similar feature could be a great idea!

Additionally, I noticed that the vector model is predefined in the custom list. How can I use a different specific model from Ollama if needed?

**Comment by kevin-on** [comment]
Could you confirm which chat model option you've selected - 'Ollama' or 'Custom (OpenAI Compatible)'? 'Ollama' option includes CORS handling, whereas using Ollama through the 'Custom (OpenAI Compatible)' option typically encounters CORS issues. If you're already using the 'Ollama' option and still experiencing problems, please let me know.

**Comment by websocketbear** [comment]
Wow! I didn’t realize there was such an option! After changing it and trying it out, it works perfectly now!

Thank you so much for providing such great answers to my unorganized questions. I really appreciate it!
