### ISSUE TITLE
Make a few suggestions

### ISSUE THREAD

**Issue by Wooden-Gear** [glowingjade/obsidian-smart-composer#148]
1. 自定义模型可以保存多个，方便切换着使用。
2. RAG添加选择模式，优先于排除模式，只有加入选择模式的文件才会加入索引。
3. 连天界面选择文件作为上下文：
        1. 以标签为识别目标，加入某个标签下的所有文件。
        2. 能够添加某个文件中某个标题下的内容作为上下文，而不是整个文件作为上下文。

我英文水平很差，只能用AI翻译，如果有不理解的地方希望谅解，并进行交流。

1. Multiple custom models can be saved, making it convenient to switch between them.
2. RAG adds a selection mode, which takes priority over exclusion mode. Only files added to the selection mode will be included in the index.
3. Selecting files as context in the chat interface:
   1. Using tags as identification targets, including all files under a specific tag.
   2. Ability to add content under specific headings from a file as context, rather than using the entire file as context.

I have a poor command of English, so I can only rely on AI translation. If there are any parts you don't understand, please feel free to discuss with me.

**Comment by kevin-on** [comment]
Please rewrite this issue in English to help others understand and participate in the discussion. Thank you!

**Comment by Wooden-Gear** [comment]
Please rewrite this issue in English to help others understand and participate in the discussion. Thank you!

Just forgot to translate。I have a poor command of English, so I can only rely on AI translation. If there are any parts you don't understand, please feel free to discuss with me.

**Comment by kevin-on** [comment]
Thanks for rewriting the issue. Let me address each point:

1. Using a Cursor-style settings UI would make it more convenient for people who work with multiple custom models. I'll add this to the backlog.
2. We can add include patterns alongside exclude patterns. I'll add this to the backlog as well.
3. Both tag-based file selection and heading-level context selection are good suggestions. Tag support is already in our plans, and the ability to select specific sections by heading would indeed be a valuable addition. I'll note this in the backlog too.

We'll work on implementing these improvements. Thanks for the thoughtful suggestions.

**Comment by kevin-on** [comment]
I've created #149 , #150 , #151 to track these items separately. Closing this issue now. Feel free to discuss if you have any concerns.

**Comment by glowingjade** [comment]
Hey everyone - this feature (multiple custom models) has been implemented in https://github.com/glowingjade/obsidian-smart-composer/pull/239 and is now available! 👋
