### ISSUE TITLE
feat: Add include patterns for RAG

### ISSUE THREAD

**Issue by kevin-on** [glowingjade/obsidian-smart-composer#151]
Requested in #148

**Comment by HighPriest** [comment]
This feature has stopped working recently?  
Putting \*.md or "\*.md" into the Include or Exclude pattern settings, does not find any files.

If I put \*.md into Include patterns, database rebuild executes on 0 files.

**Comment by glowingjade** [comment]
@HighPriest can you share your include/exclude patterns? You can test if the pattern is defined correctly by clicking the "test patterns" button.
By the way, `*.md` only includes files in the top directory. If you'd like to include all files, either keep the include patterns empty or use `**/*.md`

**Comment by HighPriest** [comment]
Thanks @glowingjade 
The description suggests to use *.md, so I did not consider this means it is only going to check top dir. Thought it is a simple regex field.

Maybe it would be a good idea to highlight this fact in the description?

**Comment by glowingjade** [comment]
@HighPriest Thanks for suggestion! I've fixed the description and it'll be included in next release: https://github.com/glowingjade/obsidian-smart-composer/pull/268
