### ISSUE TITLE
FR: Auto-Detect Local Models

### ISSUE THREAD

**Issue by iamhenry** [glowingjade/obsidian-smart-composer#153]
I use Msty as a GUI alternative for Ollama

I'd love to be able to use custom embed models that are already installed on my laptop.

It would be great it it could automatically the models i have already installed for both the chat and embed model

here's an example of another plugin

![image](https://github.com/user-attachments/assets/12dbb855-bba9-4933-9fcb-a303fc41ec79)

**Comment by glowingjade** [comment]
Thank you for the suggestion! Support for custom embedding models is part of our planned improvements. We'll also look into automatically detecting locally installed models when implementing this feature. Stay tuned for updates!

**Comment by kevin-on** [comment]
Can you tell me the name of the plugin in the screenshot?

**Comment by iamhenry** [comment]
https://github.com/pfrankov/obsidian-local-gpt

> Can you tell me the name of the plugin in the screenshot?
