### ISSUE TITLE
Chatting with Entire Vault won't work

### ISSUE THREAD

**Issue by avnibu** [glowingjade/obsidian-smart-composer#160]
### **Description:**

When attempting to send a message via the "Chat with Entire Vault" feature, the following error overlay appears, and no further chat response is received:

```
Aborted(). Build with -sASSERTIONS for more info.
```

Furthermore, rebuilding the entire index also fails (an overlay message is displayed).

Note that chatting with the active note works fine.

### **Environment Details:**
- **Obsidian Version:** 1.7.7
- **Smart Composer Plugin Version:** 1.0.9
- **Operating System:** Windows 11

**Comment by glowingjade** [comment]
<img width="1084" alt="Screenshot 2024-12-09 at 6 52 28 PM" src="https://github.com/user-attachments/assets/76992880-6676-4f44-8355-709a58913c8d">

Could you check the installer version?

**Comment by glowingjade** [comment]
The installer version requires manual updates, as it does not update automatically. Could you please try updating the installer version manually and verify if the issue still occurs?

For detailed instructions, please refer to our troubleshooting guide: https://github.com/glowingjade/obsidian-smart-composer/wiki/3.-Troubleshooting#plugin-not-loading​​​​​​​​​​​​​​​​

**Comment by avnibu** [comment]
It works! I just ran obsidian installer v1.7.7 all works as expected. Thank you!

**Comment by pengxy0** [comment]
I also encountered a similar problem when selecting a folder to summarize documents. How can I solve it?
`Aborted(). Build with -sASSERTIONS for more info.`
Environment Details:
Obsidian Version: 1.7.7
Smart Composer Plugin Version: 1.0.12
Operating System: Windows 10

**Comment by avnibu** [comment]
> @glowingjade I also encountered a similar problem when selecting a folder to summarize documents. How can I solve it? `Aborted(). Build with -sASSERTIONS for more info.` Environment Details: Obsidian Version: 1.7.7 Smart Composer Plugin Version: 1.0.12 Operating System: Windows 10

Just download the latest obsidian installer from the official website and run it.
