### ISSUE TITLE
Embed model custom url

### ISSUE THREAD

**Issue by AsleepX** [glowingjade/obsidian-smart-composer#168]
I'm using https: // api.chatanywhere.tech /v1 as my openai API.

**Comment by kevin-on** [comment]
To set OpenAI-compatible endpoints, select "Custom (OpenAI Compatible)" for either the chat model or the apply model. At present, we do not support custom embedding models or saving multiple custom model options.

**Comment by AsleepX** [comment]
Thank you for your answer! This plugin is very convenient to use!

**Comment by glowingjade** [comment]
Hey everyone - this feature has been implemented in https://github.com/glowingjade/obsidian-smart-composer/pull/239 and is now available! 👋
