### ISSUE TITLE
[FR] Rendering mathematical formula

### ISSUE THREAD

**Issue by wwjCMP** [glowingjade/obsidian-smart-composer#179]
Hope the plugin can render mathematical formulas that appear in the answers.

**Comment by kevin-on** [comment]
Hi! Is this feature request similar to what was discussed in #144 ?

**Comment by wwjCMP** [comment]
> Hi! Is this feature request similar to what was discussed in #144 ?

yes，it is.

**Comment by kevin-on** [comment]
We will close this issue as it is a duplicate of #144. Thank you for the request.
