### ISSUE TITLE
[Feature Request] Any plan to support DeepSeek v3 api?

### ISSUE THREAD

**Issue by hanbyul-kim** [glowingjade/obsidian-smart-composer#180]
DeepSeek v3 is going viral due to its high capability and low price, so I'd like to use the model in smart composer too.
Since it's an openai compatible api, it would not be difficult to add another api to the plugin.

base url: https://api.deepseek.com
model: `deepseek-chat`

**Comment by kevin-on** [comment]
You can try the OpenAI-compatible API, select "Custom (OpenAI Compatible)" for either the chat model or the apply model. If you encounter any CORS issues, please let me know.

**Comment by hanbyul-kim** [comment]
Oh, I didn't know the option. Thank you for letting me know!

**Comment by hanbyul-kim** [comment]
Well, I tried with the method you suggested, but I got this error message.

```
Failed to generate response Error: 401 Authentication Fails (no such user)
```

This is a sample request code from deepseek. Do you have any idea for this error?
```nodejs
// Please install OpenAI SDK first: `npm install openai`

import OpenAI from "openai";

const openai = new OpenAI({
        baseURL: 'https://api.deepseek.com',
        apiKey: '<DeepSeek API Key>'
});

async function main() {
  const completion = await openai.chat.completions.create({
    messages: [{ role: "system", content: "You are a helpful assistant." }],
    model: "deepseek-chat",
  });

  console.log(completion.choices[0].message.content);
}

main();
```

**Comment by hanbyul-kim** [comment]
I'm sorry, I might make a mistake. I issued a new api key and I can get it work.
