### ISSUE TITLE
Request for OpenAI API Proxy Design

### ISSUE THREAD

**Issue by GuanLdong** [glowingjade/obsidian-smart-composer#186]
Hello,

I would like to request the design of an OpenAI API proxy that would allow users to access the ChatGPT API through a third-party proxy. This could help facilitate smoother access to the API in various regions.

You might consider referencing the design from [Bin-Huang/chatbox](https://github.com/Bin-Huang/chatbox) as a potential starting point for this proxy.

I hope that international tensions do not hinder our ability to use these convenient tools. I also want to extend my gratitude to the developers of Smart Composer for creating such an excellent tool.

Thank you!

**Comment by kevin-on** [comment]
Can you elaborate more on third-party proxies? Are they unavailable when using the [custom OpenAI-compatible model option](https://github.com/glowingjade/obsidian-smart-composer/wiki/1.4-Advanced-Configuration#custom-openai-compatible-models)?

**Comment by GuanLdong** [comment]
Thank you for your response. I just checked, and it meets the requirements. Thank you once again!

**Comment by kevin-on** [comment]
You're welcome! CORS issues can indeed occur when using custom OpenAI-compatible models. If you encounter this issue, please comment on #158 for further assistance.
