### ISSUE TITLE
feat: Add ollama bge-m3 embedding model

### ISSUE THREAD

**Issue by anpigon** [glowingjade/obsidian-smart-composer#53]
다국어 임베딩을 지원하는 올라마의 BGE-M3 임베딩 모델 추가를 요청드립니다.

해당 모델은 아래 링크에서 확인할 수 있습니다.
https://ollama.com/library/bge-m3

훌륭한 플러그인 개발에 감사드립니다.

**Comment by glowingjade** [comment]
요청주신 모델 추가해서 배포했습니다! 0.1.8 버전으로 다운로드 받으시면 설정 가능합니다. 의견 감사드립니다.

The requested model has been added and deployed! You can download version 0.1.8 to configure it. Thank you for your feedback.
