### ISSUE TITLE
Add Gemini model 

### ISSUE THREAD

**Issue by imeed166** [glowingjade/obsidian-smart-composer#94]
I'm using the free gemini developper api key. It would be nice to have it work with your plugin. Thank you

**Comment by kevin-on** [comment]
Thanks for bringing this up! We have [Gemini support](https://github.com/users/glowingjade/projects/1/views/3?pane=issue&itemId=84980949) on the project tasks and are planning to add this as soon as possible.

**Comment by imeed166** [comment]
Ah sorry, didn't see it there. looking forward to it.

**Comment by kevin-on** [comment]
@imeed166 [PR #97](https://github.com/glowingjade/obsidian-smart-composer/pull/97) will resolve this issue. Maybe it will be available in the next release.

**Comment by glowingjade** [comment]
@imed-ghomari This feature has been added through https://github.com/glowingjade/obsidian-smart-composer/pull/120 and was just released.
