### ISSUE TITLE
feat: Support Google's Gemini

### ISSUE THREAD

**Issue by kevin-on** [glowingjade/obsidian-smart-composer#98]

**Comment by chenyuz3** [comment]
can we also add openrouter as available LLM API provider as well? It pretty much has every LLM API from anyone, and the switch cost would be minimized too..

**Comment by kevin-on** [comment]
Hi, we'll add support for custom OpenAI endpoints soon. Thanks!

**Comment by kevin-on** [comment]
@chenyuz3 You can now use OpenRouter through our OpenAI-compatible endpoints. See our [wiki](https://github.com/glowingjade/obsidian-smart-composer/wiki/1.4-Advanced-Configuration#custom-openai-compatible-models) for more details.
